### ISSUE TITLE
编译支付宝小程序

### ISSUE THREAD

**Issue by Surile** [xioxin/taro-ui-sample#1]
![image](https://user-images.githubusercontent.com/28652894/49682265-7d869d00-faec-11e8-8558-a61421382cd7.png)

**Comment by xioxin** [comment]
暂时不支持支付宝小程序，有空我会研究一下 看能不能支持

**Comment by xioxin** [comment]
你可以尝试一下，因为我没办法真机测试，不确保可以完美使用
cli需要升级到最新稳定版，否则会报你截图的错误
更新taro-f2到最新

**Comment by Surile** [comment]
好的。我有空看下是不是能支持下。

**Comment by 3463135482** [comment]
在微信小程序里面也会报错，生成的wxml里面，提示unexpected character '2'
<block>
    <view class="index">
        <view style="width:100%;height:500px">
            <f-2-canvas bindoninit="drawRadar" __triggerObserer="{{ _triggerObserer }}" __fn_onInit="{{true}}" data-e-drawRadar-so="this"></f-2-canvas>
        </view>
    </view>
</block>

**Comment by 3463135482** [comment]
<block>
    <view class="index">
        <view style="width:100%;height:500px">
            <f-2-canvas bindoninit="drawRadar" __triggerObserer="{{ _triggerObserer }}" __fn_onInit="{{true}}" data-e-drawRadar-so="this"></f-2-canvas>
        </view>
    </view>
</block>

**Comment by liutengfei1993** [comment]
> 在微信小程序里面也会报错，生成的wxml里面，提示unexpected character '2'

升级下微信开发工具试试 我升级前也是报错，升级后就好了
