### ISSUE TITLE
动态更新图表

### ISSUE THREAD

**Issue by soqt** [xioxin/taro-ui-sample#11]
组件好像没有暴露可以动态更新图表的props。如何根据网络请求更新当前的图表？

**Comment by xioxin** [comment]
https://github.com/xioxin/taro-f2/blob/f8736717267b8535bbae22d04ae9c02d3acc77e6/src/pages/index/index.tsx#L148-L152
> 这是老版本的示例代码 部分可能不一样

你只需要将获取到新数据后执行 `chart.source(data);chart.repaint();`

**Comment by soqt** [comment]
我的解决方案也是在onCanvasInit的函数里面设置一个setInterval，就是不太确定是不是最好的方法。那就先把这个issue close掉了。

**Comment by xioxin** [comment]
setInterval 只是因为是演示代码 用于动态随机数据

请求到数据之后 调用 chart.source(data);chart.repaint(); 刷新数据就好了
