### ISSUE TITLE
模糊

### ISSUE THREAD

**Issue by Here21** [xioxin/taro-ui-sample#14]
<img width="367" alt="F2模糊" src="https://user-images.githubusercontent.com/12051024/58023740-27aa2c80-7b43-11e9-9556-71e01fee6fd6.png">

![image](https://user-images.githubusercontent.com/12051024/58023777-3ee91a00-7b43-11e9-9b25-8c4940028c80.png)

**Comment by xioxin** [comment]
模拟器上确实模糊 真机上不模糊
