### ISSUE TITLE
@tarojs/cli 1.3.0-beta.5 编译报错   h5版本

### ISSUE THREAD

**Issue by ppbl** [xioxin/taro-ui-sample#18]
更新到最新版本， 编辑报错
![image](https://user-images.githubusercontent.com/33046279/58627328-8de43b80-8309-11e9-8c00-bf8341b75d20.png)
退回到 1.2.26 就可以了。

**Comment by ppbl** [comment]
@xioxin  能帮忙看下吗 谢谢 ~

**Comment by xioxin** [comment]
正在尝试解决

**Comment by ppbl** [comment]
找到具体一点的原因了， 是因为 @tarojs/webpack-runner 的版本问题，这个降到1.2版本的话就可以。

**Comment by xioxin** [comment]
https://github.com/NervJS/taro-ui-sample/commit/7604ac8f6e8362457837e312bcf86e7f6a348dd8

**Comment by xioxin** [comment]
看来是 f2 和 @tarojs/webpack-runner 冲突

**Comment by liuyang1106** [comment]
> 找到具体一点的原因了， 是因为 @tarojs/webpack-runner 的版本问题，这个降到1.2版本的话就可以。

请教一下这个问题怎么解决的

**Comment by xioxin** [comment]
暂时是修改 `package.json` 文件 `"@tarojs/webpack-runner": "1.2.27-beta.0"`
重新`npm install`

如果确定是这两者兼容问题的话，只能反馈给taro看看怎么处理。

**Comment by liuyang1106** [comment]
我这里依旧是不行的，当我更新@tarojs/webpack-runner的时候，就会报错找不到@babel-core，在安装@babel-core的时候的版本不支持

**Comment by ppbl** [comment]
@liuyang1106  把 @tarojs/webpack-runner 降到 1.2.26 然后 删除 node_modules 和 yarn.lock 重新安装 我这边是可以的
