### ISSUE TITLE
在 taro 1.2 版本下面报错

### ISSUE THREAD

**Issue by DiamondYuan** [xioxin/taro-ui-sample#2]
Cannot read property 'defaultView' of undefined; [Component] Event Listener Error @ npm/taro-f2/dist/weapp/components/f2-canvas/f2-canvas#(anonymous)
TypeError: Cannot read property 'defaultView' of undefined

**Comment by DiamondYuan** [comment]
如果一开始隐藏图表     console.log(canvas, width, height, F2); 的结果显示 width height 为0。这个时候就会报错。

**Comment by xioxin** [comment]
在图表需要显示的时候再加载

例如 在AtModal中使用
![image](https://user-images.githubusercontent.com/5716100/50193817-49746d00-0373-11e9-8ec7-d6c325176318.png)

**Comment by DiamondYuan** [comment]
对，我也是这么解决的。

可能需要在文档标记一下。
