### ISSUE TITLE
tooltip 不支持 showXTip

### ISSUE THREAD

**Issue by DiamondYuan** [xioxin/taro-ui-sample#3]
https://github.com/antvis/wx-f2

最新版已经支持了。

**Comment by DiamondYuan** [comment]
https://github.com/simaQ/wx-f2/blob/809f44ddf8c38c37ec0d7a0ec9eaa1627d07bbf0/src/index.js#L19

这个方法需要加上。
f2需要升级到最新版本。问题就可以解决了。

**Comment by xioxin** [comment]
收到

**Comment by xioxin** [comment]
已解决
