### ISSUE TITLE
按需引用

### ISSUE THREAD

**Issue by dumbbell0720** [xioxin/taro-ui-sample#4]
因为只需要绘制折线图，引的包太大了，taro-f2 怎么实现按需引用呢?

**Comment by xioxin** [comment]
下个版本会考虑按需引用
现在的话 你可以将 https://github.com/xioxin/taro-f2/tree/2d2ac82a019e0df1ff8bd3add5ade9fa382eee4d/src/components/f2-canvas 拷贝到自己的项目中
根据官方文档调整引用 https://www.yuque.com/antv/f2/require-on-demand

**Comment by xioxin** [comment]
按需引用终于搞定了
