### ISSUE TITLE
无法平移

### ISSUE THREAD

**Issue by beiyu98** [xioxin/taro-ui-sample#5]
图标在按照蚂蚁官方文档进行平移处理时，方法报错
`
chart.interaction is not a function; [Component] Event Listener Error @ npm/taro-f2/dist/weapp/components/f2-canvas/f2-canvas#(anonymous)
TypeError: chart.interaction is not a function

chart.scrollBar is not a function; [Component] Event Listener Error @ npm/taro-f2/dist/weapp/components/f2-canvas/f2-canvas#(anonymous)
TypeError: chart.scrollBar is not a function

`

**Comment by xioxin** [comment]
能提供下文档的那一部分吗? 我使用下 看一下

**Comment by beiyu98** [comment]
> 能提供下文档的那一部分吗? 我使用下 看一下
@xioxin  具体到文档就是这两个地方：
https://www.yuque.com/antv/f2/api-interaction
https://www.yuque.com/antv/f2/api-scroll-bar

**Comment by xioxin** [comment]
因为缺少部分组件的引用 现在正在调整按需引用 下一个版本修复这个问题 这周应该可以搞定

**Comment by xioxin** [comment]
由于框架插件暂时无法导出函数，现在可能没办法解决。 https://github.com/NervJS/taro/issues/1260

你可以将 https://github.com/xioxin/taro-f2/tree/2d2ac82a019e0df1ff8bd3add5ade9fa382eee4d/src/components/f2-canvas
目录复制到自己的项目中,  并安装 `wolfy87-eventemitter` `@antv/f2` 这两个包


根据官方教程 引入需要的组件

**Comment by beiyu98** [comment]
@xioxin 好的，谢谢

**Comment by xioxin** [comment]
按需引用已经解决了
