### ISSUE TITLE
在微信小程序端使用出错

### ISSUE THREAD

**Issue by pengx17** [xioxin/taro-ui-sample#7]
我注意到两个问题:
1. npm打包好的dist里的微信代码是ts的，没有经过tsc，导致使用出错
2. 微信小程序对于自定义组件的规范里面规定组件名为小写字母加数字，F2不符合规范

**Comment by xioxin** [comment]
你好，这个库是[Taro](https://github.com/NervJS/taro)的扩展库

代码是通过taro编译后才能运行在小程序中

**Comment by pengx17** [comment]
暂时通过源码copy/paste+改名修复

**Comment by Dhuliang** [comment]
git clone 下来 install 是报错的

**Comment by xioxin** [comment]
@Dhuliang 麻烦提供下错误信息

**Comment by Dhuliang** [comment]
@xioxin 
F2Canvas is not defined

![image](https://user-images.githubusercontent.com/40012139/53633545-bef19900-3c52-11e9-9313-c1838c8b0072.png)

需要在usingComponents里面声明么?

**Comment by Dhuliang** [comment]
目前是按照示例走的 , 进行bind之后 , taro编译后就不会寻找上级的作用域了

**Comment by xioxin** [comment]
需要在usingComponents中声明 主要影响的是 h5模式
