### ISSUE TITLE
Taro  h5中使用报错

### ISSUE THREAD

**Issue by vurtnr** [xioxin/taro-ui-sample#8]
![image](https://user-images.githubusercontent.com/8241528/53695817-4d088380-3dfb-11e9-92cb-4396dd2aa972.png)
饼图
![image](https://user-images.githubusercontent.com/8241528/53695827-64e00780-3dfb-11e9-8e93-e9d1cd53ffb9.png)
能完整展现，然后console里输出了最上面的报错信息

**Comment by xioxin** [comment]
![image](https://user-images.githubusercontent.com/5716100/53704695-f67e6200-3e59-11e9-9321-206ac1bf50bb.png)
点一下这里 看一下具体是哪一行代码

**Comment by vurtnr** [comment]
![image](https://user-images.githubusercontent.com/8241528/53720957-f18ed200-3e9c-11e9-9a69-4fa14db23b8c.png)

**Comment by xioxin** [comment]
已解决 升级到2.1.1

**Comment by vurtnr** [comment]
thk
